name: CI

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jvm-version: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{matrix.jvm-version}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.jvm-version}}

      - name: Build with Gradle
        run: ./gradlew clean build
